module.exports  = {
    scripts: ['app/**/*.js', './app/plugins/*.js', '!app/app.js'],
    styles: ['./app/styles/**/*.scss', '!./app/plugins/**/*', './bower_components/angular-toastr/dist/angular-toastr.css'],
    images: './app/images/**/*',
    index: './app/index.html',
    folders: ['./app/plugins/**/*'],
    partials: ['app/**/*.html', '!app/index.html', '!./app/plugins/**/*'],
    distDev: './dist.dev',
    distProd: './dist.prod',
    distScriptsProd: './dist.prod/scripts',
    distViewsProd: './dist.prod/components',
    scriptsDevServer: 'devServer/**/*.js',
    fonts: './app/fonts/**/*.*',
    indexFile: ['./app/app.js'],
    nodeModules: [
        //'./node_modules/angular/angular.js',
        //'./node_modules/angular-new-router/dist/router.es5.js'
    ],
    bowerComponents: [
        './bower_components/jquery/dist/jquery.min.js',
        './bower_components/lodash/lodash.min.js',
        './bower_components/angular/angular.min.js',
        './bower_components/angular-animate/angular-animate.min.js',
        './bower_components/angular-file-upload/angular-file-upload.min.js',
        './bower_components/angular-jwt/dist/angular-jwt.min.js',
        './bower_components/angular-toastr/dist/angular-toastr.min.js',
        './bower_components/angular-ui-router/release/angular-ui-router.min.js',
        './bower_components/restangular/dist/restangular.min.js',
        './bower_components/jquery.cookie/jquery.cookie.js',
        './bower_components/jquery-placeholder/jquery.placeholder.js',
        './bower_components/fastclick/lib/fastclick.js',
        './bower_components/foundation/js/foundation.min.js',
        './bower_components/modernizr/modernizr.js'
    ],
    components: [
        './app/components/common/common.module.js',
        './app/components/common/ke-form/ke-textarea/keTextarea.directive.js',
        './app/components/common/ke-form/ke-switch/keSwitch.directive.js',
        './app/components/common/ke-form/ke-select/keSelect.directive.js',
        './app/components/common/ke-form/ke-multiselect/keMultiselect.directive.js',
        './app/components/common/ke-form/ke-input-text/keInputText.directive.js',
        './app/components/common/ke-form/ke-button/keButton.directive.js',
        './app/components/common/ke-text-editor/keTextEditor.directive.js',
        './app/components/common/ke-text-editor/keModalButton.directive.js',
        './app/components/common/ke-text-editor/keListButton.directive.js',
        './app/components/common/ke-text-editor/keImageModal.controller.js',
        './app/components/common/ke-text-editor/keFrame.directive.js',
        './app/components/common/ke-tweet-button/keTweetButton.directive.js',
        './app/components/common/ke-tabs/keTabs.directive.js',
        './app/components/common/ke-tabs/keTab.directive.js',
        './app/components/common/ke-reverse-button/keReverseButton.directive.js',
        './app/components/common/ke-related-selector/keReleatedSelector.directive.js',
        './app/components/common/ke-image-selector/keImageSelector.directive.js',
        './app/components/common/ke-icon-button/keIconButton.directive.js',
        './app/components/common/ke-grid/keGrid.directive.js',
        './app/components/common/ke-files-manager/keFilesManager.directive.js',
        './app/components/common/ke-fb-comments/keFbComments.directive.js',
        './app/components/common/ke-fb-button/keFbButton.directive.js',
        './app/components/services/services.js',
        './app/components/services/user.service.js',
        './app/components/services/tag.service.js',
        './app/components/services/post.service.js',
        './app/components/services/message.service.js',
        './app/components/services/leftSlider.service.js',
        './app/components/services/file.service.js',
        './app/components/services/category.service.js',
        './app/components/menu/menu.controller.js',
        './app/components/menu/menu.directive.js',
        './app/components/login/login.routes.js',
        './app/components/login/login.controller.js',
        './app/components/home/home.controller.js',
        './app/components/grid/grid.routes.js',
        './app/components/grid/grid.controller.js',
        './app/components/about/about.controller.js',
        './app/components/contact/contact.controller.js',
        './app/components/article/article.routes.js',
        './app/components/article/article.directive.js',
        './app/components/article/article.controller.js',
        './app/components/admin/admin.routes.js',
        './app/components/admin-file/adminFile.controller.js',
        './app/components/admin-category/adminCategoryList.controller.js',
        './app/components/admin-contact/adminContact.controller.js',
        './app/components/admin-article/adminArticleList.controller.js',
        './app/components/admin-article/adminArticle.controller.js',
        './app/components/admin/admin.controller.js',
        './app/config.js'
    ],
    views: ['./app/components/**/*.html']
};